  services:
    keycloak:
      image: quay.io/keycloak/keycloak:latest
      command: [ "start-dev" ]
      environment:
        JAVA_OPTS_APPEND: "-Dcom.redhat.fips=false"
        KC_HOSTNAME_STRICT: "false"
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
        KC_LOG_LEVEL: info,org.infinispan:error,org.hibernate:warn
        KC_HTTPS_KEY_STORE_FILE: /genCerts/server-keystore.jks
        KC_HTTPS_KEY_STORE_PASSWORD: changeit
        KC_HTTPS_TRUST_STORE_FILE: /genCerts/truststore.jks
        KC_HTTPS_TRUST_STORE_PASSWORD: changeit
        HTTPS_CLIENT_AUTH: require
      ports:
        - 8080:8080
        - 8443:8443
      volumes:
        - ./genCerts:/genCerts

